<?php

/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a 
 * particular render array is to be rendered as HTML.
 *
 *
 * If you change this method, clear theme registry and routing 
 * table 'drush cc theme-registry' and 'drush cc router'.
 */
/**
 * Implements hook_theme().
 */
function dhl_location_theme($existing, $type, $theme, $path) {
  return [
    'dhl_check_location' => [
      'render element' => 'form',
	    'template' => 'check-location',
    ],
  ];
}
?>